# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - run:
          name: Install dredd
          command: sudo npm install dredd@x.x.x
      - run:
          name: version check
          command: npm info dredd version

      # specify any bash command here prefixed with `run: `
      - run: dredd apiary.apib http://127.0.0.1:8080
