version: 2
jobs:
  build:
    docker:
      - image: 'circleci/golang:1.9-node'
    steps:
      - checkout
      - run: go bulid main.go
      - run: npm install dredd@13.1.2 --global
      - run: dredd
